Cq/view attachment
PoodleApp/poodle pull request #36
Opened 2019-07-29 19:08 UTC by carinabquiroz

While looking at a presentable in a conversation, attachments are displayed with a photo icon and the filename below it, but cannot be selected and opened.

2019-07-30 14:59 UTC, breitman commented on packages/client/src/DisplayContent.tsx
> +    <div {...props}>[Attachment.{subtype}}</div>
Very very small fix, but you have a `}` closing the string instead of matching the `[` at the beginning.

2019-07-30 15:06 UTC, breitman reviewed
Looks good to me; I just suggested the tiniest change!

2019-07-30 19:04 UTC, hallettj requested changes
This is great work!

2019-07-30 19:04 UTC, hallettj commented on packages/client/src/Conversation.test.tsx
> +it("displays an attachment", async () => {
Tests! Just what I like to see!

2019-07-30 19:04 UTC, hallettj commented on packages/client/src/DisplayContent.tsx
> +    <div {...props}>[Attachment.{subtype}]</div>
This seems sensible.

2019-07-30 19:04 UTC, hallettj commented on packages/client/src/DisplayContent.tsx
> +        if (disposition === "attachment") {
This works for now. In a follow-up feature I would like to design UI for an attachments area at the bottom of the card where the presentable is displayed, or UI elements at the bottom of the card that visually set off attachments. As it stands it is possible that messages will include attachment content before inline content in the MIME tree in which case inline content would not consistently appear before attachment content.

2019-07-30 19:04 UTC, hallettj commented on packages/main/src/models/Message.ts
> +  return foldPrimaryContent(f, zero, () => true, struct)
IIRC this change was not necessary for this feature. Would you change this line back?

2019-07-30 19:04 UTC, hallettj commented on packages/main/src/models/conversation.ts
> +    })
This could be changed back since the `revision` parameter is not used.

2019-07-30 19:04 UTC, hallettj commented on packages/main/src/models/conversation.ts
> +      disposition.toLowerCase() === "attachment"
The case-insensitive comparison is a good idea.

2019-07-30 19:04 UTC, hallettj commented on packages/main/src/resolvers/conversation.ts
> +      content && replyParser(content.content ? content.content : "", true)
I could have used a more descriptive variable name to make the intent clear. `replyParser` removes stuff like quoted replies from message content. If there is no content, then there is no point in invoking `replyParser` with an empty string.

In this case if `content.content` is `null` or `undefined` then I would like this entire function to return `null` (or `undefined`).

2019-07-30 20:35 UTC, carinabquiroz commented on packages/main/src/models/conversation.ts
> +      disposition.toLowerCase() === "attachment"
Yeah, gmail sends the disposition_type as all caps.

2019-07-31 16:29 UTC, hallettj approved these changes
Looks good!

2019-07-31 16:31 UTC, hallettj commented
I merged the search feature which made a bunch of changes to `operations.graphql`. In particular the changes update most of the queries there to use fragments so what we do not have to list the same set of conversation fields over and over for each query. You will need to resolve conflicts in that file, and regenerate `graphl.tsx`.

2019-08-01 20:56 UTC, breitman approved these changes

2019-08-02 17:19 UTC, merged

2019-11-03 22:44 UTC, hallettj commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/PoodleApp/poodle/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2019-11-04 00:55 UTC, hallettj commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/PoodleApp/poodle/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: